FlySearcher_#1
IvanKvashnin/FlySearcher pull request #3
Opened 2022-10-23 15:42 UTC by IvanKvashnin

1. Setup bot configuration
2. Add method -> return user message

2022-10-23 15:56 UTC, oagafonov requested changes

2022-10-23 16:59 UTC, IvanKvashnin commented on telegram-bot/src/main/resources/application.properties
> +token=5583391660:AAEz2XOnVfA18anota1JOQzgip1avpddZJw
То есть мне надо в терминале объявить переменную и присвоить ей токен ? 

TELEGRAMTOKEN=токен 

И потом присвоить в токен через 
@Value({TELEGRAMTOKEN})

2022-10-24 19:08 UTC, oagafonov commented on telegram-bot/src/main/resources/application.properties
> +token=5583391660:AAEz2XOnVfA18anota1JOQzgip1avpddZJw
В application.properies используешь не сам токен, а плейхолдер для переменной окружения
```
token=${BOT_TOKEN}
```
В итоге при запуске приложения, spring подставить туда переменную окружения BOT_TOKEN
Саму переменную можно задать с помощью команды export
```bash
export BOT_TOKEN=5583391660:AAEz2XOnVfA18anota1JOQzgip1avpddZJw
```
Больше ничего не нужно менять.

2022-10-26 15:22 UTC, IvanKvashnin commented on telegram-bot/src/main/java/com/ikvashnin/bot/botUtils.java
> +    private static final SendMessage message = new SendMessage();
Я бы это обсудил на следующем созвоне. Для меня многопоточность пока что магия.

2022-10-28 15:32 UTC, oagafonov approved these changes

2022-10-28 16:49 UTC, merged